### ISSUE TITLE
Some plots do not work with scikit-image 0.9.x

### ISSUE THREAD

**Issue by mriehl** [scipy-lectures/scientific-python-lectures#101]
Some functions in scikit-image [were removed with 0.9.x](http://scikit-image.org/docs/0.9.x/api_changes.html) : 

```
________________________________________________________________________________
plotting plot_filter_coins.py
/data/home/max/workspace/scipy-lecture-notes/ve/local/lib/python2.7/site-packages/skimage/filter/ctmf.py:22: skimage_deprecation: Call to deprecated function ``median_filter``. Use ``filter.r
ank.median`` instead.
  def median_filter(image, radius=2, mask=None, percent=50):
________________________________________________________________________________
plot_filter_coins.py is not compiling:
Traceback (most recent call last):
  File "/data/home/max/workspace/scipy-lecture-notes/sphinxext/gen_rst.py", line 239, in generate_file_rst
    execfile(os.path.basename(src_file), {'pl': plt})
  File "plot_filter_coins.py", line 14, in <module>
    tv_filter_coins = filter.tv_denoise(coins, weight=0.1)
AttributeError: 'module' object has no attribute 'tv_denoise'
________________________________________________________________________________
plotting plot_segmentations.py
________________________________________________________________________________
plot_segmentations.py is not compiling:
Traceback (most recent call last):
  File "/data/home/max/workspace/scipy-lecture-notes/sphinxext/gen_rst.py", line 239, in generate_file_rst
    execfile(os.path.basename(src_file), {'pl': plt})
  File "plot_segmentations.py", line 11, in <module>
    from skimage.morphology import watershed, is_local_maximum
ImportError: cannot import name is_local_maximum
________________________________________________________________________________
plotting plot_lena_tv_denoise.py
________________________________________________________________________________
plot_lena_tv_denoise.py is not compiling:
Traceback (most recent call last):
  File "/data/home/max/workspace/scipy-lecture-notes/sphinxext/gen_rst.py", line 239, in generate_file_rst
    execfile(os.path.basename(src_file), {'pl': plt})
  File "plot_lena_tv_denoise.py", line 4, in <module>
    from skimage.filter import tv_denoise
ImportError: cannot import name tv_denoise
________________________________________________________________________________
plotting plot_watershed_segmentation.py
________________________________________________________________________________
plot_watershed_segmentation.py is not compiling:
Traceback (most recent call last):
  File "/data/home/max/workspace/scipy-lecture-notes/sphinxext/gen_rst.py", line 239, in generate_file_rst
    execfile(os.path.basename(src_file), {'pl': plt})
  File "plot_watershed_segmentation.py", line 2, in <module>
    from skimage.morphology import watershed, is_local_maximum
ImportError: cannot import name is_local_maximum
```

The docstring example in `skimage.morphology` seems to suggest that `peak_local_max` can be used as a drop-in replacement but that doesn't do the trick for me : 

```
Traceback (most recent call last):
  File "plot_watershed_segmentation.py", line 18, in <module>
    local_maxi = peak_local_max(distance, image, np.ones((3, 3)))
  File "/data/home/max/workspace/scipy-lecture-notes/ve/local/lib/python2.7/site-packages/skimage/feature/peak.py", line 128, in peak_local_max
    image_max = ndi.maximum_filter(image, size=size, mode='constant')
  File "/data/home/max/workspace/scipy-lecture-notes/ve/local/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 926, in maximum_filter
    cval, origin, 0)
  File "/data/home/max/workspace/scipy-lecture-notes/ve/local/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 859, in _min_or_max_filter
    sizes = _ni_support._normalize_sequence(size, input.ndim)
  File "/data/home/max/workspace/scipy-lecture-notes/ve/local/lib/python2.7/site-packages/scipy/ndimage/_ni_support.py", line 66, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
```
